### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [saveth/intro-data-capstone-musclehub#1]
Overall, your work met the project specs -- good job!

First, I want to point out that you submitted this project under the wrong task -- I was expecting MuscleHub..

Your slide deck is very neat and presentable. I only have two critiques:
The text is rather small and hard to read. Pretend like you're going to present to a huge room of people. Could people in the back see?

Some slides are rather wordy. You can't expect audience members to read the entire slide. Try splitting up complex ideas into multiple slides so you can go more in depth.

Keep up the good work!

**Comment by saveth** [comment]
Thanks for the feedback. Should I resubmit under the Biodiversity task with the suggested fixes?
